export const sel = {
  trackList: "#track-list",
  trackRow: ".track-row",
  trackRowById: (id: number) => `[data-track-id="${id}"]`,
  searchInput: "#search-input",
  libraryTab: (label: string) => `[role="tab"][aria-selected]*=${label}`,
  sortHeader: (label: string) => `button[role="columnheader"]*=${label}`,
  settingsButton: "#btn-settings",
  scanButton: "#btn-scan-now",
  scanStatusBar: "#scan-status-bar",
  closeSettings: "#btn-close-settings",
  playlist: "#playlist",
  playlistRow: ".playlist-row",
  clearPlaylist: "#btn-clear-playlist",
  autoPlaylistToggle: "#btn-generate",
  btnPlay: "#btn-play",
  btnStop: "#btn-stop",
  btnNext: "#btn-next",
  btnPrev: "#btn-prev",
  timeDisplay: ".time-pill",
} as const;
