name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  typecheck:
    uses: ./.github/workflows/typecheck.yml

  test:
    uses: ./.github/workflows/unit-test.yml

  rust:
    uses: ./.github/workflows/rust.yml

  build:
    uses: ./.github/workflows/build.yml
    with:
      platform: ubuntu-24.04
      target: x86_64-unknown-linux-gnu
      args: ""
      artifact-name: linux-bundle

  e2e:
    needs: build
    uses: ./.github/workflows/e2e.yml
    with:
      build-artifact: linux-bundle
