name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/unit-test.yml

  build:
    uses: ./.github/workflows/build.yml

  e2e-test:
    uses: ./.github/workflows/playwright.yml
    needs: build
